### ISSUE TITLE
'sudo udevadm trigger' Results in 'Permission Denied' Errors - Chromebook

### ISSUE THREAD

**Issue by BroJac5246** [redphx/joydance#14]
Hi, I really want to use Joydance, but I'm having trouble getting it to recognize my Joy Cons. I've followed all the steps, including the extra steps for Linux users, but when I run `sudo udevadm trigger`, I get a ton of messages that read:

`Failed to write 'change' to '<folder path>': Permission denied`

I get this error 137 times, and it's super annoying and confusing. I'm pretty new to Linux, so I might be doing something wrong, and this error _may or may not_ be affected by Joydance but either way... please help me! I really want to try out Joydance!

Thanks in advance

**Comment by redphx** [comment]
Sorry I'm not familiar with Chromebook/ChromeOS. Have you tried connecting the Joy-Con after restarting?

**Comment by redphx** [comment]
Not sure whether this is useful or not: https://github.com/dnschneid/crouton/wiki/udev:-manage-inserted-devices

**Comment by BroJac5246** [comment]
> Not sure whether this is useful or not: https://github.com/dnschneid/crouton/wiki/udev:-manage-inserted-devices

It says to modify `/etc/rc.local`, but that directory doesn't exist.

**Comment by BroJac5246** [comment]
I guess I'll just try asking on Reddit.
