### ISSUE TITLE
Add Crostini Support

### ISSUE THREAD

**Issue by BroJac5246** [redphx/joydance#15]
After [some issues with udev rules](https://www.reddit.com/r/Crostini/comments/umte0t/sudo_udevadm_trigger_results_in_permission_denied/i84iw8n/?context=3), I discovered that Crostini does [not have direct Bluetooth support](https://chromium.googlesource.com/chromiumos/docs/+/HEAD/containers_and_vms.md#can-i-access-hardware-e_g_usb_bluetooth_serial). However, the official documentation states that [Web Bluetooth API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API) could be used as a workaround. I would love to see JoyDance support on Crostini, so _please_ look into this.

Thanks.

**Comment by redphx** [comment]
I'm not sure that will work, but sure it gonna take a lot of time because originally JoyDance wasn't designed to use Web Bluetooth API.

**Comment by BroJac5246** [comment]
> Another option is running JoyDance on a Raspberry Pi Zero 2 W

But then you need to acquire the hardware, which is kind of what JoyDance is designed to help you avoid.

**Comment by redphx** [comment]
> which is kind of what JoyDance is designed to help you avoid.
  
No I never said that. I love using JoyDance on my Pi because it's small, portable, and I don't need to use my laptop anymore.

**Comment by BroJac5246** [comment]
I'm just saying that it could be a reason why someone is interested in using JoyDance. The description states:
> Use Joy-Cons to play Ubisoft's Just Dance on all platforms

To me, that looks like a way to avoid the extra hardware often associated with Just Dance.

Also, unrelated: In
> Use Joy-Cons to play Ubitsoft's Just Dance on all platforms
You misspelled Ubisoft.

Also, in README.md, under the Tested heading, you wrote:
> Raspberry Pi Zero 2 W (**Bulleye**, kernel 5.15)
Did you mean Bullseye?

**Comment by redphx** [comment]
> To me, that looks like a way to avoid the extra hardware often associated with Just Dance.
  
Yeah, that's understandable.

> Did you mean Bullseye?
  
Thank you. Fixed both.
