### ISSUE TITLE
JoyDance fails to installing. "pip3 is not recognized as the name of a cmdlet, function, script file, or operable program." error

### ISSUE THREAD

**Issue by tcbloom72** [redphx/joydance#17]
Hello,

I tried downloading JoyDance but every time I tried entering the command in both Terminal and Command Prompt it displays this

![2022-05-28 14_18_37-New Issue · redphx_joydance](https://user-images.githubusercontent.com/106432672/170823303-b90610a4-34df-4100-8482-3fc360036b42.png)
![2022-05-28 14_20_03-C__Windows_System32_cmd exe](https://user-images.githubusercontent.com/106432672/170823304-55540243-2593-432a-b8e3-3e6450bfd2bf.png)
 
both Python and Pip are installed

**Comment by redphx** [comment]
In that case you'll have to use `python` and `pip` instead of `python3` and `pip3`
