### ISSUE TITLE
[Suggestion] WiimoteDance?

### ISSUE THREAD

**Issue by icebearko** [redphx/joydance#21]
Can u make an app like JoyDance but it uses WiiMote?

**Comment by redphx** [comment]
I think it's possible to make it work with Wiimote, but I don't have one at the moment.

**Comment by icebear2000** [comment]
I think you should buy the old one. It's cheaper than the new one. If you are living in Vietnam, buy one on this shopee link. Only 350000 VND for blue color, motion plus inside and that is the real one. https://shopee.vn/product/90348718/14038764433?smtt=0.657296228-1654512720.9

**Comment by icebear2000** [comment]
I think you're Vietnamese right? I saw you make an Auto collect shopee xu extension.

**Comment by redphx** [comment]
I'd prefer to borrow it from someone I know. I don't want to spend money on sth I only use a few times. Also this feature is not my top priority right now, so let's hope someone else will pick it up.

**Comment by icebear2000** [comment]
I can lend it for u

**Comment by icebearko** [comment]
Do u have Facebook, Discord or something so we can talk easier.

**Comment by Evaldash** [comment]
Wiimote drivers aren't easy to set up, and it seems that no maintained library exists for the wiimote, thus it could be really hard.

**Comment by redphx** [comment]
This project will only for Joy-Con. Feel free to fork it to add other controllers.
