### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by BroJac5246** [redphx/joydance#28]
JoyDance currently doesn't have a license. However, since you're encouraging people to use it, it would be good to add a license for legal and clarity reasons.

**Comment by redphx** [comment]
I've thought about that. But because [tocoteron/joycon-python](https://github.com/tocoteron/joycon-python) didn't have a license I couldn't do the same.

**Comment by BroJac5246** [comment]
I created an issue on their respiratory: tocoteron/joycon-python#30, so hopefully they'll add one soon. :)

**Comment by BroJac5246** [comment]
> I created an issue on their repository: tocoteron/joycon-python#30, so hopefully they'll add one soon. :)

**Comment by BroJac5246** [comment]
@redphx would you be willing to license just the code that you created, which would give _more_ flexibility?

**Comment by redphx** [comment]
Added MIT License
