### ISSUE TITLE
Movedance (suggestion)

### ISSUE THREAD

**Issue by tim51955** [redphx/joydance#29]
Basically the same thing joydance does, but with a psmove, maybe even a add on that changes the primary ps move buttons and maps them to the switch buttons

**Comment by BroJac5246** [comment]
So basically the same thing as #21, but with PS Move?

**Comment by BroJac5246** [comment]
I just realized that this is also a duplicate, see #5

**Comment by tim51955** [comment]
> I just realized that this is also a duplicate, see #5

Sorry, I did not see #5. Does the script in the last comment work for ps move?

**Comment by BroJac5246** [comment]
> > I just realized that this is also a duplicate, see #5
> 
> Sorry, I did not see #5. Does the script in the last comment work for ps move?

If you're referring to the last comment of #5 then supposedly yes. I don't know how the code works beyond the very basics, though, so I can't say for sure.

**Comment by tim51955** [comment]
the only problem i have with the script in #5 is that it doesnt detect my psmove

**Comment by BroJac5246** [comment]
I don't know a ton about how JoyDance works, but my understanding is that the mentioned variable tells the program about the accelerometer. You'll also need to tell the program how to detect and connect to the Move controller. I don't know how that's done, but try digging around the code to see how JoyCons are connected. Good luck :)

**Comment by redphx** [comment]
This project only focuses on Joy-Con only. I don't have any experences with PS Move so I won't be able to support it.
