### ISSUE TITLE
joydance isnt working on pc

### ISSUE THREAD

**Issue by ronrah20** [redphx/joydance#3]
i tried to get it running on Just Dance 2017 PC but when i click connect the script crashes and im getting it "{'pairing_method': 'old', 'host_ip_addr': '192.168.1.109', 'console_ip_addr': '192.168.1.109', 'pairing_code': '', 'joycon_serial': 'idhere'}"

**Comment by redphx** [comment]
Do you see a "config.cfg" file in the same folder?

**Comment by ronrah20** [comment]
yeah

**Comment by redphx** [comment]
Please open the pairing screen in JD (you might need to close and open it again), then open this link http://192.168.1.109:8080. 
Do you see "404 Not Found" text?

**Comment by ronrah20** [comment]
yeah

**Comment by redphx** [comment]
Please change [this line](https://github.com/redphx/joydance/blob/main/dance.py#L82=) from
```
joycon.__del__()
```
to 
```
# joycon.__del__()
```
and try again
