### ISSUE TITLE
Just Dance 2017 PC / Wii U Profile Issue

### ISSUE THREAD

**Issue by ThatsAnotherJ** [redphx/joydance#4]
So when you connect the Joycon the user always shows up as Happy. I believe this is because newer versions of the controller app don't let you log in to your Ubisoft account. If you try this with the app itself on the latest version the same problem will occur. I only tested this on the Wii U and PC version of Just Dance 2017. On Just Dance 2016 Wii U this wasn't an issue however. Is there anything that can be done to make it so you can still play with your regular Ubisoft account?

**Comment by redphx** [comment]
I think you can change the nickname in Profile right? I can do that in JD 2018 NSW.  
Sorry I don't know the different between playing with regular Ubi account vs. the profile created by the app.

**Comment by redphx** [comment]
And thanks for confirming that JoyDance works on Wii U.

**Comment by ThatsAnotherJ** [comment]
On Just Dance Controller 5.52 or earlier, you could log into your Ubisoft account which let you play with a customized profile like this.
![unknown33](https://user-images.githubusercontent.com/68207021/164008141-2edcaa31-84f6-43a7-88d5-e3656c4e0746.png)

On later versions of Just Dance Controller (including Joydance), you cannot log into your Ubisoft account. This means you will show up as this.
![unknown39](https://user-images.githubusercontent.com/68207021/164008236-6aef4df2-1481-4a87-9485-ddff296ad028.png)

I believe this is only a problem on Just Dance 2017.

**Comment by redphx** [comment]
In that case nothing I can do. Sorry. Also I prefer not asking for user's credential.
