### ISSUE TITLE
"Could not build wheels for aiohttp, hidapi, which is required to install pyproject.toml-based projects"

### ISSUE THREAD

**Issue by oakleyplays** [redphx/joydance#45]
i cant get those to install on windows 10 pro 22H2 when using command pip3 install -r requirements.txt

**Comment by BroJac5246** [comment]
I was getting this issue as well on Ubuntu 23.04. I know the solution involved virtual environments, but I can't remember what I did. There was a lot of trial and error.

Sorry I can't help more, but maybe something I said will help you at some point?

**Comment by oakleyplays** [comment]
> I was getting this issue as well on Ubuntu 23.04. I know the solution involved virtual environments, but I can't remember what I did. There was a lot of trial and error.
> 
> Sorry I can't help more, but maybe something I said will help you at some point?

Yeah, with windows it’s probably different, but maybe if i try and troubleshoot i can get it to work.

**Comment by oakleyplays** [comment]
Oh, its a thing with aiohttp version

**Comment by BroJac5246** [comment]
> Oh, its a thing with aiohttp version

It probably won't work, but have you tried installing aiohttp directly (not from the `requirements.txt` file)?

Also, can hid be used instead of hidapi (since that's an extra step for Linux users)? Once again, it likely won't work, but maybe it's worth trying?

**Comment by BroJac5246** [comment]
Also, what Python version are you running? I just came across #36 and it sounds like 3.10 is the most likely version to work.

**Comment by oakleyplays** [comment]
> Also, what Python version are you running? I just came across #36 and it sounds like 3.10 is the most likely version to work.

3.11.

**Comment by oakleyplays** [comment]
> Also, what Python version are you running? I just came across #36 and it sounds like 3.10 is the most likely version to work.

By the way, could you possibly check out my other post where it’s missing a module and cant run?

**Comment by BroJac5246** [comment]
> > Also, what Python version are you running? I just came across #36 and it sounds like 3.10 is the most likely version to work.
> 
> By the way, could you possibly check out my other post where it’s missing a module and cant run?

I saw it but I don't know how to fix it. My best advice would be to look it up.

**Comment by BroJac5246** [comment]
> > Also, what Python version are you running? I just came across #36 and it sounds like 3.10 is the most likely version to work.
> 
> 3.11.

If you're able to, you could try installing 3.10.

I do know it's possible on 3.11, though, because I've done it before.

**Comment by fedeshoker** [comment]
Hey! you have to install 3.10. 

3.11 is incompatible with requirements.txt

**Comment by BroJac5246** [comment]
Did installing 3.10 fix the problems?
