### ISSUE TITLE
[Suggestion] PS move port

### ISSUE THREAD

**Issue by Evaldash** [redphx/joydance#5]
With PS5 and Xbox series JD versions only available to play with a phone, I think it'd be cool if you could play with a PS move too. I'd attempt to port it myself, but I'm a bit swamped with finals right now, so if anyone would like to try feel free to to use my idea.

**Comment by redphx** [comment]
I never used or saw a PS Move before so I don't have opinion about it. Is its accelerometer sensor better or worse than Joy-Con?

**Comment by Evaldash** [comment]
It's about on par, I use it with my PS4. :) I believe it works with the accelerometer, but don't quote me on that.

**Comment by redphx** [comment]
PS Move's maximum accelerometer range is [±6G](https://www.psdevwiki.com/ps3/Move_Motion_Controller), but on Joy-Con it's [±8G](https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/blob/master/imu_sensor_notes.md) (up to ±16G), so I think Joy-Con is better at detecting motion. But we could add support for PS Move by changing [this variable](https://github.com/redphx/joydance/blob/main/joydance/constants.py#L21=).

**Comment by Julmik647** [comment]
> PS Move's maximum accelerometer range is [±6G](https://www.psdevwiki.com/ps3/Move_Motion_Controller), but on Joy-Con it's [±8G](https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/blob/master/imu_sensor_notes.md) (up to ±16G), so I think Joy-Con is better at detecting motion. But we could add support for PS Move by changing [this variable](https://github.com/redphx/joydance/blob/main/joydance/constants.py#L21=).

Accelerometer isn't only way to detect motion on PS Move. Motion can be also detected by camera.

**Comment by BroJac5246** [comment]
> > PS Move's maximum accelerometer range is [±6G](https://www.psdevwiki.com/ps3/Move_Motion_Controller), but on Joy-Con it's [±8G](https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/blob/master/imu_sensor_notes.md) (up to ±16G), so I think Joy-Con is better at detecting motion. But we could add support for PS Move by changing [this variable](https://github.com/redphx/joydance/blob/main/joydance/constants.py#L21=).
> 
> Accelerometer isn't only way to detect motion on PS Move. Motion can be also detected by camera.

That's too far outside the scope of JoyDance.
