### ISSUE TITLE
Error on Just Dance 2017 PC websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 404

### ISSUE THREAD

**Issue by mccrena** [redphx/joydance#51]
![PixPin_2023-12-26_04-27-16](https://github.com/redphx/joydance/assets/95366235/f8766f0f-4350-4c62-b26a-592b0a7d4980)
![image](https://github.com/redphx/joydance/assets/95366235/89f6fcec-9a03-4932-9668-d0c4f8e05d74)
When I follow the guide, I get to the point of connecting to the joycon and have a problem

**Comment by BroJac5246** [comment]
The error says that the console is rejecting the connection.

To verify, does this still happen after restarting your computer?

I'm not the developer of the project, but I'm willing to try to help you troubleshoot.

**Comment by mccrena** [comment]
I'm glad to see your reply.
I restarted my computer and saw a different error message
![image](https://github.com/redphx/joydance/assets/95366235/fc0f87c0-d9fa-4655-8f88-b99588576a86)
![image](https://github.com/redphx/joydance/assets/95366235/dd8c6f45-fe20-45ab-8c7e-277e5b2f292d)

**Comment by mccrena** [comment]
When I press CTRL+C to interrupt the program, and then execute it again, I get the HTTP 404 error, exactly like the first time I posted above

**Comment by BroJac5246** [comment]
Do you have any consoles on which you have a copy of Just Dance? (Demos of 2022 or older would also work.) It's okay if you don't, but that would provide more info.

Also, what Python version are you using? And are you on Windows 10 (that's what the pictures appear to show)?

**Comment by mccrena** [comment]
I have switch and ps5 and I found out that JD2024 on switch can be downloaded for free.
My python version is 3.10.11 and windows version is Windows 10 22H2

**Comment by BroJac5246** [comment]
> I have switch and ps5 and I found out that JD2024 on switch can be downloaded for free.
> My python version is 3.10.11 and windows version is Windows 10 22H2

JD 2023 & 2024 use a different app & protocol that JoyDance is (as of now and the foreseeable future) unable to emulate.

My best suggestion would be to try again with a different Python version, since sometimes errors are specific to certain versions— the minimum that JoyDance supports is 3.7. If you can, you could also try to install JoyDance on a different device or operating system, though that's dependent on what devices you have.

**Comment by mccrena** [comment]
I've tried versions from 3.7 to 3.10 and I get the same error "HTTP 404".
![image](https://github.com/redphx/joydance/assets/95366235/d51584b9-669e-4374-aa75-04440502368f)
And since Just Dance will be down for all but the latest version on the PS5 and NS stores, but I own a cracked NS so I can install Just Dance 2022's Copy, I don't know if this will be useful in solving the JD2017 PC problem, but I'll try if this works!

**Comment by mccrena** [comment]
I found out that JD2022 on NS requires a Nintendo account to be associated with it in order to play it with my phone, so I failed.
I was still able to play with Joydance 0.5.2 at this time last year, when JD2017 PC was still using UPLAY instead of UBISOFT CONNECT, and I was able to connect and play with the older version of the JD CONTROLLER APP (5.1.2, connecting by setting up an IP). Although the environments were different (windows 11 22H2 and Python 3.10), a few things were the same: the same APP version, and both used the mod from https://www.youtube.com/@Dreyn (which has been updated in the past year). 
I uninstalled the mod and reinstalled the original JD2017 PC version and found that it still doesn't work, reporting the same error "HTTP 404", so I don't think it's a mod problem.

**Comment by BroJac5246** [comment]
> I was still able to play with Joydance 0.5.2 at this time last year, when JD2017 PC was still using UPLAY instead of UBISOFT CONNECT, and I was able to connect and play with the older version of the JD CONTROLLER APP (5.1.2, connecting by setting up an IP). Although the environments were different (windows 11 22H2 and Python 3.10), a few things were the same: the same APP version, and both used the mod from https://www.youtube.com/@Dreyn (which has been updated in the past year). 
> I uninstalled the mod and reinstalled the original JD2017 PC version and found that it still doesn't work, reporting the same error "HTTP 404", so I don't think it's a mod problem.

Will the regular app still connect for you? Even newer versions (should?) work, though I've never used a PC version of Just Dance.

**Comment by mccrena** [comment]
After my testing, Just Dance on NS (latest version), can connect with the new app; 2022 and previous JDs on NS, since I didn't buy it before and don't have the cassette on hand now can't test it; JD2017 on PC can't connect to the phone (neither Android nor Apple), using the old app version

**Comment by BroJac5246** [comment]
> After my testing, Just Dance on NS (latest version), can connect with the new app

The new app was built specifically for the new version, so that's intended.

> JD2017 on PC can't connect to the phone (neither Android nor Apple), using the old app version

Does the game (on PC) show the _option_ to connect? I don't have it so sorry for all the questions.

**Comment by mccrena** [comment]
![image](https://github.com/redphx/joydance/assets/95366235/c4f67fb1-a113-4aa6-97fc-039453c46814)
![image](https://github.com/redphx/joydance/assets/95366235/51149e63-9d6f-4dfb-9d26-23f157b550ae)
I just borrowed a JD2022 NS cassette from a friend close to me, and my tests are as follows: when using the app on my phone, it's connecting; when using joycon, I encountered the error: Invalid pairing code

**Comment by mccrena** [comment]
![image](https://github.com/redphx/joydance/assets/95366235/2acb5aa6-a124-49ae-b061-8a31f9b557ee)
And when I select FAST mode, it successfully connects
Interestingly, when I connect to JD2022 on ns with Joycon, I can't fill in the nickname because I'm not connecting with a smartphone, but the game prompts me that the nickname can't be blank, so I can't get into the game at all.

**Comment by mccrena** [comment]
> Does the game (on PC) show the _option_ to connect? I don't have it so sorry for all the questions.

![image](https://github.com/redphx/joydance/assets/95366235/36f64740-3364-4a1c-a225-f63fa9a1ee43)
No. The connect in this game doesn't have any options to choose from, there is only a phone pairing screen
![image](https://github.com/redphx/joydance/assets/95366235/4eb9d76b-9c8a-4e96-b1e8-8cda8e34de8f)
Though it offers another option: No Mobile Service, but then you don't have any way to experience that game, the only option left is QUIT.

**Comment by BroJac5246** [comment]
> JD2017 on PC can't connect to the phone (neither Android nor Apple), using the old app version

I'm wondering if the game changed? Ubisoft recently discontinued the online servers for JD2016-18, and I'm wondering if that had an effect exclusively on the PC version? I'm pretty sure it still works for me on Xbox, though I won't be able to check for a few days.


@redphx should this still work? Are you able to confirm if it worked and/or worked for you on the PC version?

(mccrena, I don't know if redphx will respond but they're the creator of the project and would know much better than me)

**Comment by mccrena** [comment]
> > JD2017 on PC can't connect to the phone (neither Android nor Apple), using the old app version
> 
> I'm wondering if the game changed? Ubisoft recently discontinued the online servers for JD2016-18, and I'm wondering if that had an effect exclusively on the PC version? I'm pretty sure it still works for me on Xbox, though I won't be able to check for a few days.

![image](https://github.com/redphx/joydance/assets/95366235/b6349c77-48e4-499d-9b72-2ca65f65908a)
I think Joydance still works on JD2017 PC after the update, here's a discord I joined for the JD2017 PC mod, in which someone mentioned the use of Joydance in 2023.11.1 (obviously after the update)

**Comment by BroJac5246** [comment]
> ![image](https://github.com/redphx/joydance/assets/95366235/b6349c77-48e4-499d-9b72-2ca65f65908a)
> I think Joydance still works on JD2017 PC after the update, here's a discord I joined for the JD2017 PC mod, in which someone mentioned the use of Joydance in 2023.11.1 (obviously after the update)

I wonder if there's a reason they were tethering from their phone...

I don't really know what it could be. It's interesting to see that fast pairing works.

My only remaining suggestion would be to try from a different device, but that's dependent on you having other hardware— if you do, you can try on there (be warned that setting it up on Linux may be hard), otherwise your best bet would be to hope redphx responds (which is somewhat unlikely). Sorry! This sort of thing really isn't my forte...

If anything else does come up or there are new developments, though, I'm definitely willing to try my best to help.

**Comment by mccrena** [comment]
Thank you very much indeed, BroJac5246!
New Windows/Mac/Linux devices are unlikely in the near future, I think Maybe the day I reinstall my system, it might be a "new" device!
I actually have a NS with some great JD games on it, but god you really have to try the mod I mentioned above, he only runs on JD2017 PC and it has almost all of JD's songs in it (by far the most complete I've ever seen), which is why I've always wanted to play JD on PC!
I'll still always try to solve this problem in the future (when I change the network environment, when I have a new idea to solve the problem , maybe when @redphx replies etc)
All in all, thanks for being willing to take the time to help me out, Have a good day!

**Comment by mccrena** [comment]
Things worked out, but for a bit of a funny reason.
As I said before, the JD17 PC wouldn't connect to my phone and that's exactly why Joydance wouldn't work.
The solution is at this link https://www.youtube.com/watch?v=zJeWN-aqU8I

**Comment by BroJac5246** [comment]
> Things worked out, but for a bit of a funny reason.
> As I said before, the JD17 PC wouldn't connect to my phone and that's exactly why Joydance wouldn't work.
> The solution is at this link https://www.youtube.com/watch?v=zJeWN-aqU8I

Glad to see it worked! I was a little confused why you couldn't connect your phone but that explains it!
