### ISSUE TITLE
Directory ¨.¨ is not installable. Neither 'setup.py' nor 'pyproject.toml' 

### ISSUE THREAD

**Issue by danfnes3** [redphx/joydance#58]
I´m getting this issue while trying to install on windows 10, and honestly Idk what to do.

**Comment by BroJac5246** [comment]
Can you provide some additional details? What Python version are you using? What command(s) are giving you that error?

**Comment by danfnes3** [comment]
> Can you provide some additional details? What Python version are you using? What command(s) are giving you that error?

Hi! I'm Using Python 3.10.0 and the error appears when I use "pip3 install -r requirements.txt"

**Comment by BroJac5246** [comment]
> > Can you provide some additional details? What Python version are you using? What command(s) are giving you that error?
> 
> Hi! I'm Using Python 3.10.0 and the error appears when I use "pip3 install -r requirements.txt"

Can you provide the output of the command?

Sometimes manually installing modules via pip helps, but seeing the log would help me figure out what to do. 

(Sorry it took so long to get back to you; I've been super busy)

**Comment by danfnes3** [comment]
I'm really new on this, so it would be really helpful if you tell me how I can get What you're asking plz

**Comment by BroJac5246** [comment]
When you run `pip3 install -r requirements.txt`, the terminal should give an output that includes the error. Can you copy all of that, paste it into pastebin.com or a similar website, and then share the link so I can look at the log and hopefully give suggestions?

**Comment by danfnes3** [comment]
https://pastebin.com/B2vnWmD3 Like this?

**Comment by BroJac5246** [comment]
> https://pastebin.com/B2vnWmD3 Like this?

Yes, that's great! After running the command, can you enter the `ls` command and give the output of that?

**Comment by danfnes3** [comment]
> > https://pastebin.com/B2vnWmD3 Like this?
> 
> Yes, that's great! After running the command, can you enter the `ls` command and give the output of that?

which 1s command?

**Comment by BroJac5246** [comment]
> > > https://pastebin.com/B2vnWmD3 Like this?
> > 
> > Yes, that's great! After running the command, can you enter the `ls` command and give the output of that?
> 
> which 1s command?
> 

ls (the letter that proceeds m)

**Comment by danfnes3** [comment]
> > > > https://pastebin.com/B2vnWmD3 Like this?
> > > 
> > > 
> > > Yes, that's great! After running the command, can you enter the `ls` command and give the output of that?
> > 
> > 
> > which 1s command?
> 
> ls (the letter that proceeds m)

It does not recognize it as a command

https://pastebin.com/YE0vU4E7

**Comment by BroJac5246** [comment]
> > > > Yes, that's great! After running the command, can you enter the `ls` command and give the output of that?
> > > 
> > > which 1s command?
> > 
> > ls (the letter that proceeds m)
> 
> It does not recognize it as a command
> 
> https://pastebin.com/YE0vU4E7

Can you try again in PowerShell?

**Comment by danfnes3** [comment]
> > > > > Yes, that's great! After running the command, can you enter the `ls` command and give the output of that?
> > > > 
> > > > 
> > > > which 1s command?
> > > 
> > > 
> > > ls (the letter that proceeds m)
> > 
> > 
> > It does not recognize it as a command
> > https://pastebin.com/YE0vU4E7
> 
> Can you try again in PowerShell?

Sorry I dont know how to use that

**Comment by BroJac5246** [comment]
> > > > > > Yes, that's great! After running the command, can you enter the `ls` command and give the output of that?
> > > > > 
> > > > > 
> > > > > which 1s command?
> > > > 
> > > > 
> > > > ls (the letter that proceeds m)
> > > 
> > > 
> > > It does not recognize it as a command
> > > https://pastebin.com/YE0vU4E7
> > 
> > Can you try again in PowerShell?
> 
> Sorry I dont know how to use that

Open Windows Search and search there, or scroll down in the Start Menu to the PowerShell folder and click on the one called "PowerShell." (There might be some others, but you can ignore those). PowerShell is more versatile than Command Prompt while still retaining the core functionality.

**Comment by danfnes3** [comment]
https://pastebin.com/swHG6Vc8

I got this when I do the ls command in the joydance directory on powershell

**Comment by danfnes3** [comment]
> > > > > > > Yes, that's great! After running the command, can you enter the `ls` command and give the output of that?
> > > > > > 
> > > > > > 
> > > > > > which 1s command?
> > > > > 
> > > > > 
> > > > > ls (the letter that proceeds m)
> > > > 
> > > > 
> > > > It does not recognize it as a command
> > > > https://pastebin.com/YE0vU4E7
> > > 
> > > 
> > > Can you try again in PowerShell?
> > 
> > 
> > Sorry I dont know how to use that
> 
> Open Windows Search and search there, or scroll down in the Start Menu to the PowerShell folder and click on the one called "PowerShell." (There might be some others, but you can ignore those). PowerShell is more versatile than Command Prompt while still retaining the core functionality.

https://pastebin.com/swHG6Vc8

I got this when I do the ls command in the joydance directory on powershel

**Comment by BroJac5246** [comment]
Have you `cd`'d into the directory first? If not, try running
```
cd Desktop\joydance-0.5.2
pip3 install -r requirements.txt
```

**Comment by danfnes3** [comment]
OMG it worked thank you!

**Comment by BroJac5246** [comment]
> OMG it worked thank you!

Awesome! So glad I could help. Since you're new to the command line, welcome! `cd` and `ls` are your best friends. You use `cd` to switch directories and `ls` to view the contents of the active one. Unless the command you're running specifically wants you to reference a directory that's not active, it's always a best practice to `cd` into the directory in which you want to use the command first. It can be overwhelming at first, but you'll get used to it in no time!

Since it worked, would you mind closing this issue, ideally marking it as "not planned"? I don't have the ability to close issues, but I'm trying to help keep things organized.

If you have any more issues, feel free to ping me and ask.
