### ISSUE TITLE
Windows - Can't seem to run dance.py

### ISSUE THREAD

**Issue by JosPlays** [redphx/joydance#64]
Hello,

First of all, thanks to the person that keeps answering these questions and keeps the project alive. I really would like to use it for Just Dance 2017 on PC, but I can't get it to work:

I get the following error:

Commands I ran in Powershell:
cd C:\Users\Admin\Desktop\joydance-0.5.2
python3 dance.py

Error:
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\joydance-0.5.2\dance.py", line 12, in <module>
    import hid
  File "C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\hid\__init__.py", line 31, in <module>
    raise ImportError(error)
ImportError: Unable to load any of the following libraries:libhidapi-hidraw.so libhidapi-hidraw.so.0 libhidapi-libusb.so libhidapi-libusb.so.0 libhidapi-iohidmanager.so libhidapi-iohidmanager.so.0 libhidapi.dylib hidapi.dll libhidapi-0.dll

Can anyone help me? I have followed the installation guide in the git, but I don't know anything from Python, so it's really hard to see where it went wrong.

**Comment by JosPlays** [comment]
Never mind, got it working by going back to Python 10.10
Now I have to wait till my bluetooth stick arrives so I can test it.

**Comment by BroJac5246** [comment]
Let me know if you have any further issues; I'll be happy to try to help you troubleshoot.
