### ISSUE TITLE
IP Address not 192.168.

### ISSUE THREAD

**Issue by NobodySleep** [redphx/joydance#9]
My personal IP address for my network is not the required 192.168. but it starts with 10.0. Is there a workaround to this or some way to convert my IP address to be what is needed? Sorry, my knowledge is quite limited.

**Comment by redphx** [comment]
Hi there, thanks for reporting. I'll fix it soon.

**Comment by redphx** [comment]
@NobodySleep please test this version: https://github.com/redphx/joydance/archive/refs/heads/feature/fix_local_ip.zip

**Comment by NobodySleep** [comment]
It worked out! I was able to connect the joycon and use it!

**Comment by redphx** [comment]
Glad to hear that. Which version of JD & platform do you have?
